flat_ppackage.Rmd:
  path: dev/flat_ppackage.Rmd
  state: active
  R:
  - R/my_other_median.R
  - R/paste_perc.R
  - R/internal-datasets-schools-list.R
  tests:
  - tests/testthat/test-paste_perc.R
  - tests/testthat/test-my_other_median.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_ppackage.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
