# WARNING - Generated by {fusen} from dev/flat_ppackage.Rmd: do not edit by hand

test_that("paste_perc works properly and show error if needed", {
  expect_true(paste_perc(0.5) == "50%")
  expect_true(all(paste_perc(c(0.444444, 0.2222), 1) == c("44.4%", "22.2%")))
  expect_error(paste_perc("text"))
})

