# WARNING - Generated by {fusen} from dev/flat_ppackage.Rmd: do not edit by hand

#' Convert decimal value to a percent to be printed
#'
#' @param x double or vector of doubles
#' @inheritParams base::paste0
#' @inheritParams base::round 
#'
#' @return
#' Character vector of a percent value
#' @export
#'
#' @examples
#' x = 0.988
#' paste_perc(x)
#'
#' x = c(0.444444, 0.2222, 0.5555)
#' paste_perc(x, 1)
paste_perc <- function(x, digits = 0) {
  if (!is.numeric(x)) {stop("x should be numeric")}
  base::paste0(base::round(x*100, digits = digits), "%")
}
